version: '2'

services:

  web:
    build: .
    container_name: web
    depends_on:
      - db
    restart: always
    ports:
      - 8080:5000
    environment:
      - MODE="production"
      - DB_USER="repair_system"
      - DB_PASSWORD="passw0rd"
      - DB_HOST=db:3306
      - DB_DATABASE="repair_system"
      - MAIL_USERNAME=""
      - MAIL_PASSWORD=""
    volumes:
      - ./data/Backup:/code/Backup
      - ./data/log:/code/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - repair_system

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="passw0rd"
      - MYSQL_DATABASE="repair_system"
      - MYSQL_USER="repair_system"
      - MYSQL_PASSWORD="passw0rd"
    volumes:
      - ./data/db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - repair_system

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - repair_system

networks:
  repair_system:
