version: '2'

services:

  web:
    build: .
    container_name: web
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - MODE=production
      - DB_USER=repair_system
      - DB_PASSWORD=passw0rd
      - DB_HOST=db:3306
      - DB_DATABASE=repair_system
      - MAIL_USERNAME=USERNAME
      - MAIL_PASSWORD=PASSWORD
      - RECAPTCHA_PUBLIC_KEY=KEY
      - RECAPTCHA_PRIVATE_KEY=KEY
    volumes:
      - ./data/backup:/code/backup
      - ./data/log:/code/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=repair_system
      - MYSQL_USER=repair_system
      - MYSQL_PASSWORD=passw0rd
    volumes:
      - ./data/db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - CERTBOT_EMAIL=
      - STAGING=0
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
      - ELLIPTIC_CURVE=secp384r1
      - USE_ECDSA=1
      - RENEWAL_INTERVAL=8d
      - DEBUG=0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/ssl:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
      - /dev/null:/var/log/nginx/access.log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

networks:
  net:
