version: '2'

services:

  web:
    build: ./src
    container_name: web
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DB_USER=repair_system
      - DB_PASSWORD=passw0rd
      - DB_HOST=db:3306
      - DB_DATABASE=repair_system
      - MAIL_USERNAME=USERNAME
      - MAIL_PASSWORD=PASSWORD
      - RECAPTCHA_PUBLIC_KEY=KEY
      - RECAPTCHA_PRIVATE_KEY=KEY
      - TZ=Asia/Taipei
    volumes:
      - ./data/backup:/code/backup
      - ./data/log:/code/log
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - net

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=repair_system
      - MYSQL_USER=repair_system
      - MYSQL_PASSWORD=passw0rd
      - TZ=Asia/Taipei
    volumes:
      - ./data/db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - net

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - CERTBOT_EMAIL=user@example.com
      - STAGING=0
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=4096
      - ELLIPTIC_CURVE=secp384r1
      - USE_ECDSA=1
      - RENEWAL_INTERVAL=8d
      - DEBUG=0
      - TZ=Asia/Taipei
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/ssl:/etc/letsencrypt
      - ./nginx/templates:/etc/nginx/templates
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - net

networks:
  net:
